import Link from "next/link";
import {notFound} from "next/navigation";
import {CsrfInput} from "@/components/CsrfInput";
import {DashboardShell} from "@/components/DashboardShell";
import {prisma} from "@/lib/prisma";
import {roleLabels} from "@/lib/roles";
import {requireRole} from "@/lib/session";
import {updatePlatformUserAction} from "../../actions";

const statusOptions=["ACTIVE","INACTIVE","SUSPENDED","ARCHIVED"] as const;
export default async function PlatformUserEditPage({params}:any){const currentUser=await requireRole("PLATFORM_OWNER");const {id}=await params;const userId=Number(id);if(!Number.isFinite(userId)){notFound();}const user=await prisma.user.findUnique({where:{id:userId},select:{id:true,name:true,email:true,role:true,status:true,business:{select:{name:true}},branch:{select:{name:true}}}});if(!user){notFound();}return (<DashboardShell user={currentUser} eyebrow="System Administrator" title="Edit user"><section className="rounded-md border border-[#E5E7EB] bg-white p-5 shadow-sm"><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-semibold text-[#111827]">{user.name}</h2><p className="mt-1 text-sm text-[#6B7280]">Role, business, and branch assignment are kept unchanged for audit safety.</p></div><Link href={`/platform/users/${user.id}`} className="inline-flex h-10 items-center justify-center rounded-md border border-[#E5E7EB] px-4 text-sm font-semibold text-[#111827]">Cancel</Link></div><form action={updatePlatformUserAction} className="mt-5 grid gap-4 md:grid-cols-2"><CsrfInput scope="platform:users" /><input type="hidden" name="userId" value={user.id} /><label className="text-sm font-medium text-[#111827]">Name<input name="name" defaultValue={user.name} className="mt-1 h-10 w-full rounded-md border border-[#E5E7EB] px-3 text-sm outline-none focus:border-[#F97316]" /></label><label className="text-sm font-medium text-[#111827]">Email<input name="email" type="email" defaultValue={user.email} className="mt-1 h-10 w-full rounded-md border border-[#E5E7EB] px-3 text-sm outline-none focus:border-[#F97316]" /></label><label className="text-sm font-medium text-[#111827]">Lifecycle status<select name="status" defaultValue={user.status} className="mt-1 h-10 w-full rounded-md border border-[#E5E7EB] px-3 text-sm outline-none focus:border-[#F97316]">{statusOptions.map(function(status){return <option key={status} value={status}>{status}</option>;})}</select></label><div className="rounded-md border border-[#E5E7EB] bg-[#F9FAFB] p-4 text-sm text-[#374151]"><p><strong>Role:</strong> {roleLabels[user.role]}</p><p className="mt-2"><strong>Business:</strong> {user.business?.name ?? "-"}</p><p className="mt-2"><strong>Branch:</strong> {user.branch?.name ?? "-"}</p></div><div className="md:col-span-2 flex justify-end"><button type="submit" className="h-10 rounded-md bg-[#F97316] px-4 text-sm font-semibold text-white transition hover:bg-orange-600">Save changes</button></div></form></section></DashboardShell>);}
