"use server";

import bcrypt from "bcryptjs";
import {randomInt} from "crypto";
import {revalidatePath} from "next/cache";
import {redirect} from "next/navigation";
import {z} from "zod";
import {logAuditEvent} from "@/lib/audit";
import {validateCsrfForm} from "@/lib/csrf";
import {prisma} from "@/lib/prisma";
import {requireRole} from "@/lib/session";

const scope="platform:users";
const userActionSchema=z.object({userId:z.coerce.number().int().positive("User not found.")});
const statusActionSchema=userActionSchema.extend({nextStatus:z.enum(["ACTIVE","SUSPENDED","INACTIVE"])});
const updateUserSchema=userActionSchema.extend({name:z.string().trim().min(1,"User name is required."),email:z.string().trim().email("User email is required."),status:z.enum(["ACTIVE","INACTIVE","SUSPENDED","ARCHIVED"])});
function getString(formData:FormData,key:string){const value=formData.get(key);return typeof value==="string"?value:"";}
function fail(path:string,message:string):never{redirect(path+"?error="+encodeURIComponent(message));}
function validateSecurity(formData:FormData,path:string){try{validateCsrfForm(formData,scope);}catch{fail(path,"Security check failed. Please refresh and try again.");}}
function generateTemporaryPassword(){const groups=["ABCDEFGHJKLMNPQRSTUVWXYZ","abcdefghijkmnopqrstuvwxyz","23456789","!@#*"];const allCharacters=groups.join("");const characters:string[]=[];for(const group of groups){characters.push(group[randomInt(group.length)]);}for(let count=0;count!==12;count+=1){characters.push(allCharacters[randomInt(allCharacters.length)]);}for(let index=characters.length-1;index!==0;index-=1){const swapIndex=randomInt(index+1);const current=characters[index];characters[index]=characters[swapIndex];characters[swapIndex]=current;}return characters.join("");}
async function getTargetUser(userId:number){return prisma.user.findUnique({where:{id:userId},select:{id:true,name:true,email:true,role:true,status:true,businessId:true,branchId:true,sessionVersion:true}});}
async function ensureCanLifecycleChange(actor:any,target:any,action:string,path:string){if(target.role!=="PLATFORM_OWNER"){return;}let dangerous=false;if(action==="suspend"){dangerous=true;}if(action==="archive"){dangerous=true;}if(dangerous){if(target.id===actor.id){fail(path,"You cannot suspend or archive your own System Administrator account.");}const remaining=await prisma.user.count({where:{role:"PLATFORM_OWNER",status:"ACTIVE",id:{not:target.id}}});if(remaining===0){fail(path,"At least one active System Administrator must remain.");}}}
async function writeUserAudit(tx:any,actorId:number,target:any,action:string,metadata:any){await logAuditEvent({tx,actorUserId:actorId,businessId:target.businessId,branchId:target.branchId,action,entityType:"user",entityId:target.id,metadata:{targetEmail:target.email,targetRole:target.role,...metadata}});}
function successPath(message:string){return "/platform/users?success="+encodeURIComponent(message);}
export type PlatformUserPasswordResetState={error?:string;temporaryPassword?:string;targetName?:string;targetEmail?:string};
export async function resetPlatformUserPasswordAction(_state:PlatformUserPasswordResetState,formData:FormData){try{validateCsrfForm(formData,scope);}catch{return{error:"Security check failed. Please refresh and try again."};}const actor=await requireRole("PLATFORM_OWNER");const parsed=userActionSchema.safeParse({userId:getString(formData,"userId")});if(!parsed.success){const message=parsed.error.issues[0]?.message?parsed.error.issues[0].message:"User not found.";return{error:message};}const target=await getTargetUser(parsed.data.userId);if(!target){return{error:"User not found."};}const temporaryPassword=generateTemporaryPassword();const passwordHash=await bcrypt.hash(temporaryPassword,12);const changedAt=new Date();await prisma.$transaction(async function(tx){await tx.user.update({where:{id:target.id},data:{passwordHash,forcePasswordChange:true,passwordChangedAt:changedAt,sessionVersion:{increment:1}}});await writeUserAudit(tx,actor.id,target,"USER_PASSWORD_RESET",{forcedLogout:true,forcePasswordChange:true,temporaryPasswordDisplayedOnce:true});});revalidatePath("/platform/users");revalidatePath("/platform/users/"+target.id);return{temporaryPassword,targetName:target.name,targetEmail:target.email};}
export async function forceLogoutPlatformUserAction(formData:FormData){const path="/platform/users";validateSecurity(formData,path);const actor=await requireRole("PLATFORM_OWNER");const parsed=userActionSchema.safeParse({userId:getString(formData,"userId")});if(!parsed.success){fail(path,"User not found.");}const target=await getTargetUser(parsed.data.userId);if(!target){fail(path,"User not found.");}await prisma.$transaction(async function(tx){await tx.user.update({where:{id:target.id},data:{sessionVersion:{increment:1}}});await writeUserAudit(tx,actor.id,target,"USER_FORCE_LOGOUT",{previousSessionVersion:target.sessionVersion});});revalidatePath("/platform/users");redirect(successPath("User sessions were forced to log out."));}
export async function setPlatformUserStatusAction(formData:FormData){const path="/platform/users";validateSecurity(formData,path);const actor=await requireRole("PLATFORM_OWNER");const parsed=statusActionSchema.safeParse({userId:getString(formData,"userId"),nextStatus:getString(formData,"nextStatus")});if(!parsed.success){fail(path,parsed.error.issues[0]?.message?parsed.error.issues[0].message:"Invalid user status.");}const target=await getTargetUser(parsed.data.userId);if(!target){fail(path,"User not found.");}const action=parsed.data.nextStatus==="ACTIVE"?"enable":"suspend";await ensureCanLifecycleChange(actor,target,action,path);await prisma.$transaction(async function(tx){await tx.user.update({where:{id:target.id},data:{status:parsed.data.nextStatus,sessionVersion:{increment:1}}});await writeUserAudit(tx,actor.id,target,parsed.data.nextStatus==="ACTIVE"?"USER_ENABLED":"USER_SUSPENDED",{previousStatus:target.status,nextStatus:parsed.data.nextStatus});});revalidatePath("/platform/users");redirect(successPath(parsed.data.nextStatus==="ACTIVE"?"User enabled.":"User suspended."));}
export async function archivePlatformUserAction(formData:FormData){const path="/platform/users";validateSecurity(formData,path);const actor=await requireRole("PLATFORM_OWNER");const parsed=userActionSchema.safeParse({userId:getString(formData,"userId")});if(!parsed.success){fail(path,"User not found.");}const target=await getTargetUser(parsed.data.userId);if(!target){fail(path,"User not found.");}await ensureCanLifecycleChange(actor,target,"archive",path);await prisma.$transaction(async function(tx){await tx.user.update({where:{id:target.id},data:{status:"ARCHIVED",sessionVersion:{increment:1}}});await writeUserAudit(tx,actor.id,target,"USER_ARCHIVED",{previousStatus:target.status,nextStatus:"ARCHIVED",historyPreserved:true});});revalidatePath("/platform/users");redirect(successPath("User archived. History was preserved."));}
export async function updatePlatformUserAction(formData:FormData){const rawUserId=getString(formData,"userId");const path="/platform/users/"+rawUserId+"/edit";validateSecurity(formData,path);const actor=await requireRole("PLATFORM_OWNER");const parsed=updateUserSchema.safeParse({userId:rawUserId,name:getString(formData,"name"),email:getString(formData,"email"),status:getString(formData,"status")});if(!parsed.success){fail(path,parsed.error.issues[0]?.message?parsed.error.issues[0].message:"Validation failed.");}const target=await getTargetUser(parsed.data.userId);if(!target){fail("/platform/users","User not found.");}let lifecycleAction="enable";if(parsed.data.status==="SUSPENDED"){lifecycleAction="suspend";}if(parsed.data.status==="ARCHIVED"){lifecycleAction="archive";}await ensureCanLifecycleChange(actor,target,lifecycleAction,path);const statusChanged=target.status!==parsed.data.status;await prisma.$transaction(async function(tx){await tx.user.update({where:{id:target.id},data:{name:parsed.data.name,email:parsed.data.email.toLowerCase(),status:parsed.data.status,sessionVersion:statusChanged?{increment:1}:undefined}});await writeUserAudit(tx,actor.id,target,"USER_UPDATED",{previousStatus:target.status,nextStatus:parsed.data.status,emailChanged:target.email!==parsed.data.email.toLowerCase(),nameChanged:target.name!==parsed.data.name});if(statusChanged){const auditAction=parsed.data.status==="ACTIVE"?"USER_ENABLED":parsed.data.status==="ARCHIVED"?"USER_ARCHIVED":"USER_SUSPENDED";await writeUserAudit(tx,actor.id,target,auditAction,{previousStatus:target.status,nextStatus:parsed.data.status});}});revalidatePath("/platform/users");revalidatePath("/platform/users/"+target.id);redirect("/platform/users/"+target.id+"?success="+encodeURIComponent("User updated."));}
