import Link from "next/link";
import {notFound} from "next/navigation";
import {DashboardShell} from "@/components/DashboardShell";
import {StatusBadge} from "@/components/StatusBadge";
import {formatDate} from "@/lib/format";
import {prisma} from "@/lib/prisma";
import {getDisplayUserName,roleLabels} from "@/lib/roles";
import {requireRole} from "@/lib/session";

export default async function PlatformUserDetailPage({params}:any){const currentUser=await requireRole("PLATFORM_OWNER");const {id}=await params;const userId=Number(id);if(!Number.isFinite(userId)){notFound();}const user=await prisma.user.findUnique({where:{id:userId},select:{id:true,name:true,email:true,role:true,status:true,createdAt:true,updatedAt:true,lastLoginAt:true,forcePasswordChange:true,sessionVersion:true,business:{select:{name:true}},branch:{select:{name:true}}}});if(!user){notFound();}return (<DashboardShell user={currentUser} eyebrow="System Administrator" title="User details"><section className="rounded-md border border-[#E5E7EB] bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-semibold text-[#111827]">{getDisplayUserName(user)}</h2><p className="mt-1 break-all font-mono text-sm text-[#6B7280]">{user.email}</p></div><div className="flex gap-2"><Link href="/platform/users" className="inline-flex h-10 items-center rounded-md border border-[#E5E7EB] px-4 text-sm font-semibold text-[#111827]">Back</Link><Link href={`/platform/users/${user.id}/edit`} className="inline-flex h-10 items-center rounded-md bg-[#F97316] px-4 text-sm font-semibold text-white">Edit</Link></div></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3"><Info label="Role" value={roleLabels[user.role]} /><div className="rounded-md border border-[#E5E7EB] bg-[#F9FAFB] p-4"><p className="text-xs font-semibold uppercase text-[#6B7280]">Status</p><div className="mt-2"><StatusBadge status={user.status} /></div></div><Info label="Business" value={user.business?.name ?? "-"} /><Info label="Branch" value={user.branch?.name ?? "-"} /><Info label="Last login" value={user.lastLoginAt?formatDate(user.lastLoginAt):"Never"} /><Info label="Force password change" value={user.forcePasswordChange?"Yes":"No"} /><Info label="Session version" value={String(user.sessionVersion)} /><Info label="Created" value={formatDate(user.createdAt)} /><Info label="Updated" value={formatDate(user.updatedAt)} /></div></section></DashboardShell>);}
function Info({label,value}:any){return <div className="rounded-md border border-[#E5E7EB] bg-[#F9FAFB] p-4"><p className="text-xs font-semibold uppercase text-[#6B7280]">{label}</p><p className="mt-2 break-words font-semibold text-[#111827]">{value}</p></div>;}
